### ISSUE TITLE
Enable the module by default

### ISSUE THREAD

**Issue by jaimeperez** [NIIF/simplesamlphp-module-attributeaggregator#2]
Now we are using composer, those modules installed with it won't be in place unless the user explicitly installs them. When a user installs this module, it will be disabled by default, and he or she will need to enable it by including an _enable_ file in the root of the module. That file will be removed when updating the module with composer again.

Therefore, default behaviour should be to enable external modules by default.

**Comment by szabogyula** [comment]
Thank you Jaime it's done!
