### ISSUE TITLE
Para van ha self-signed az AA tanúsítványa

### ISSUE THREAD

**Issue by sitya** [NIIF/simplesamlphp-module-attributeaggregator#4]
Lehet, hogy csak az újabb PHP miatt, de tény, hogy a SOAPClient-t úgy, hogy `'allow_self_signed' => TRUE`. Nem tudom, hogy ezt az opciót meg lehetne-e adni már innen, az attributeaggregator-ból, mert bár az opciók összegyűjtése nem itt történik, hanem a `vendor/simplesamlphp/saml2/src/SAML2/SOAPClient.php`-ban, de a probléma e modul használatakor jön elő.

**Comment by szabogyula** [comment]
Ezt a globális config.php-ban kellett beállítani? `'allow_self_signed' => TRUE`

**Comment by sitya** [comment]
Lófütty. `vendor/simplesamlphp/saml2/src/SAML2/SOAPClient.php` 30. sorába.

**Comment by bajnokk** [comment]
Bakfitty! A `www/attributequery.php` 172. sorában ezt:
```
$result = $binding->send($query,$src);
```
Le kell cserélni erre:
```
$result = $binding->send($query,$src,$dst);
```
